### ISSUE TITLE
[1.0] $event is not being passed

### ISSUE THREAD

**Issue by getflourish** [nglar/ngTouchmove#2]
When I try to bind a touchmove event, the defined method is being called. But when trying to access the "$event", it returns undefined. Any idea what could be wrong?

**Comment by marktopper** [comment]
From my [test](http://plnkr.co/edit/xt3P3aoCWhSi3BdUMHJq?p=preview) it all works fine.

Check it out and let me know if there are any problems.

**Comment by marktopper** [comment]
Now I have been looking more into this, and it seems that you are right.

Will be fixing this in a few moments.

**Comment by marktopper** [comment]
I have made a [test](http://plnkr.co/edit/9l9QLKGmWvLc3Jm08FYj?p=preview) which actually gets it.

You just have to use `$scope.event`, since that is not passed to the function.
