### ISSUE TITLE
[1.0] Detect direction

### ISSUE THREAD

**Issue by jamesbondo** [nglar/ngTouchmove#8]
thanks! can it decide moving left or right from the directive ?

**Comment by marktopper** [comment]
This should be possible once I have fixed #2.
Once that is done I will get back to you with a solution for this.

**Comment by marktopper** [comment]
If I am right, you wanna know whether or not it moves a certain direction.

Something like:

```
$scope.onTouchmove = function() {
  if (movingRight) {
    // do something
  } else if (movingLeft) {
    // do something
  }
};
```

Am I right @jamesbondo?

**Comment by marktopper** [comment]
In case I am right then I would use [ngTouchstart](https://github.com/nglar/ngTouchstart) and [ngTouchmove](https://github.com/nglar/ngTouchmove) (or together with [ngTouch](https://github.com/nglar/ngTouch)) library.

Then save the coordinations for the touchstart event, and then on touchmove I would check the coordinates against the new event.

**Comment by marktopper** [comment]
Closing it for now - however let me know if this does not resolve your issue.
